### ISSUE TITLE
Can the SVCB scope even work

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/snip#5]
@bemasc says

> On further consideration, I think a SVCB scope may be unworkable.  Consider a CDN customer who copies the CDN's ServiceForm RRSet into their own domain, and (alas) fails to keep it up to date.  If the CDN adds a new incompatible protocol, everything will work fine, but SNIP will flag this as an attack, possibly making the customer's site unreachable.
>
> The problem is that the SVCB scope doesn't identify _which_ SVCB RRSet it's referring to, and it's not always easy to enumerate all the SVCB RRSets that include a particular endpoint.

I think that the first is just an operational issue (a worthwhile one to note).  I don't think that identifying the set is likely to be useful as a response to this though.  Ensuring that the CDN does not enable protocols without ensuring the consistency with DNS configuration (or other discovery configuration) is what I would prefer.

**Comment by bemasc** [comment]
> Ensuring that the CDN does not enable protocols without ensuring the consistency with DNS configuration (or other discovery configuration) is what I would prefer.

My point is that this is impossible: the CDN doesn't control, or even necessarily know about, the DNS configuration.  Sure, ideally customers will just CNAME to the CDN, but we can't prevent them from copying the configuration into their own domain (and even modifying it).  This is a Bad Idea, but it's the kind of thing that will appear to work until the CDN makes a change.

ECH suffers from the same problem, but at least there (1) the CDN can detect the problem (customers stuck on old keys) in its own traffic, and (2) the fallback keys avoid user-visible breakage when old keys are rotated out of the frontends.

I think IP:port scope is basically sufficient protection, but if you want bigger-scope protection with SVCB, I think the best bet is to include the ServiceForm RRSet's owner name in the scope indication.  That also avoids assuming that each endpoint only participates in a single SVCB RRSet.

**Comment by martinthomson** [comment]
I'm convinced.  IP:port is maybe-workable.  Anything beyond that can be done later.  The changes in the most recent draft greatly simplify the design.
